spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: none
  show-sql: true

spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/products
  username: root
  password: password